### ISSUE TITLE
feedback on project outline assignment

### ISSUE THREAD

**Issue by dcmorse** [belkisac/liftoff-assignments#1]
Hi Kisa,
Your project outline looks good. 

I like the idea of the calendar view in particular - sounds like a fun view to write. 

Food for thought: if you find you don't have time to do every thing you're imagining, how would you trim down your list of features and still keep the spirit of the project intact?

**Comment by belkisac** [comment]
I would most likely leave the notification features for the future, and if I couldn't implement the calendar the way I want to I'd try to do something else, like make a list view of things expiring that month. Ideally I wouldn't scrap the account creation because it's supposed to be a personal profile, so not having that feature would lessen it.
